# Generated by Django 5.1.7 on 2025-03-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0004_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='chaiheadq\\default.png', upload_to='profile_pics/'),
        ),
    ]
