# Generated by Django 5.1.7 on 2025-03-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0007_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='highlighted',
            field=models.BooleanField(default=False),
        ),
    ]
